


include ../../Makefile.inc


test-flake8: ## Run flake8 tests
	@/bin/true

test-isort: ## run isort check
	@/bin/true


test-quality: test-flake8 test-isort
	@/bin/true

test: build-image test-quality
	@/bin/true