sudo: false
language: python

services:
  - docker

before_install:
    # start rabbitmq
    - docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3.6.6-management
    # start mongodb
    - docker run -d --rm --name=maiev_mongodb -p 27017:27017 mongo


addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox

cache:
  directories:
    - $HOME/.cache/pip

python:
- "3.6"


jobs:
  include:
    - stage: test
      env: SERVICE=common/health_mongodb
    - env: SERVICE=scaler/registry_docker
    - env: SERVICE=scaler/scaler_docker
    - env: SERVICE=overseer/dependency_solver
    - env: SERVICE=overseer/overseer
    - env: SERVICE=overseer/load_manager
    - env: SERVICE=overseer/upgrade_planer
    - env: SERVICE=monitorer/monitorer_rabbitmq
    - env: SERVICE=monitorer/trigger
    - stage: global
      script:
      - TARGET=latest make -C services/maiev-base build-image
      - TARGET=global make build-image
      - make test -C global

script:
  - TARGET=latest make -C services/maiev-base build-image
  - make test -C services/$SERVICE


