sudo: false
language: bash

services:
  - docker

before_install:
    - docker pull yupeek/maiev:maiev-base-build-${TRAVIS_BUILD_NUMBER}
    - docker tag yupeek/maiev:maiev-base-build-${TRAVIS_BUILD_NUMBER} maiev-base:latest
    # start rabbitmq
    - docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3.6.6-management
    # start mongodb
    - docker run -d --rm --name=maiev_mongodb -p 27017:27017 mongo

cache:
  directories:
    - $HOME/.cache/pip

stages:
  - base
  - test
  - global
  - staging
  - production

jobs:
  include:
    # first, we build the base image and we push it do the registry
    - stage: base
      before_install: []
      env: &envvar
        - secure: "qtxHIfzPTQcgnPvVy1khUU/ceJQVJFoiF5+L/qfKW8FhIgWdkHExD4PrpkQjzrqsKUi1pqWcj3CXNwSLDzfMqS6rs/CDQFocM3jmCeq8JNm6A7C8C+T4lEZXtGMbdhKSU9cY2rC64vknuHcQ7RDvdn9avumgbXJMzolv67a/6Zy4qAf+BrBLpjWeazHmr4hUV7Ds8DDBgtkrxofqRv6/IrIGWccJAgHZK4hNm7E0JeWCujoSjZu7GhQY5MyuOrErpZ7ood8WD09aFBe5CbNzW6IEFOIGVoQ7ccKi/xY6XXmN/VausqGBFgeXbeGxwbyXAVOjNHr/n0SVkw0jCXj8yWmVkmc1JtWmK1KyqkqXCuB5tJp+obY1dTxgUNqgMGFA+9CqovO6kGEUiJKhRvw7zsnFNGnmrHwbw0UHQOzuJh0NCJXbTw1044GA6OeHYmM2DqQFLLCgUOaKHmLrHZBkW5mzF/kn1PubLuS8uMxnZqWWU1tmfr+8gRe119JL6jzDxEFatHiYLOjfjGof5tsUghEmvw3WXlLrTkDvT0ACxYqQ1N32nntZmraHNpb/pEk49wHHZE9m3nXI+P6b13X0Y0GizTUeaALcEwr2TcChC8ws+vtuKSeXKNbQLUHRzkidsDDHqffP+aflqtB5ZvuR2UQ7+nmRMdqHy3s0AUnidyc="
        - secure: "oZx7FoU0aaS4H3+ST5M+yrv01frGz+083TOzE5q57kD3lXBSexxftc7tuXMaYKdxP7CFCHAcwkfPOUIbYgwwHZrVgHzZVuqyKCji3sgBQDagl5hJTUPwFG0r1L9A5eZFWKm2S0t848mDi6ukPWy/56CYOQPMzu3CKiKYDCqNrZv7hyZx/ZaIwdI4LRqsDp6JjjxvPfBYp2hxr8CL+DILm4iT3pzVhNept3X9Wl1i+YkZ2IrpJYrlDDgq63EWURkA+Nz3N9Tkb+7YeqyJP/gTMnEjl/lbzmuMLxBEDKuU6VJQHArnDbAzNPxrg3HS/ikyVSpHXcGNaIFITWq3xqUIdtcaTeZ/0D+JvEStrFkAJQaLs5PL0LJI8fV+xL5evyW0BXhWuv8+U8JV48hFcO+qMbgff+wYDA9FuLNTyCcOYhx2WwFKP1G85vGO59h6cPehBfms7nTxHoGEiblfeaH4jLFzm/3E23hyA+pJLrurdUnv3I5xYPxgWk+hDa5wzQYW4+QzSbNbsK/1bhJfgrY5kj5ZQ1vCjNDMAgf0tDmel2KXKtkmV2P9qsTcy7hE/uLCO6w9/8ObB7kHWab6G18lMYJF12ZHbBOwkkJ+1ZmfEIFfKE0WazpWh4YER51Xj5v9v4t6aZwVAoRhpfb+YCZSoNklqGK0Sm69siDrIXmLmec="
        - "DOCKER_REPO=yupeek"
        - "TARGET=prod"
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - TARGET=latest make -C services/maiev-base build-image
      - TARGET=latest IMAGE_VERSION=build-${TRAVIS_BUILD_NUMBER} SERVICE_FORCE_PUSH=maiev-base make deploy -C services/maiev-base

    # then we test all service with the previous built base image (pulled in before_install)
    - stage: test
      env: SERVICE=common/health_mongodb
    - env: SERVICE=scaler/registry_docker
    - env: SERVICE=scaler/scaler_docker
    - env: SERVICE=overseer/dependency_solver
    - env: SERVICE=overseer/overseer
    - env: SERVICE=overseer/load_manager
    - env: SERVICE=overseer/upgrade_planer
    - env: SERVICE=monitorer/monitorer_rabbitmq
    - env: SERVICE=monitorer/trigger

    # we build the global image
    - stage: global
      script:
      - TARGET=global make build-image
      - make test -C global

    # we deploy to docker-hub if the branch are develop.
    - stage: staging
      before_install: []
      env: *envvar
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - TARGET=latest make -C services/maiev-base build-image
        - TARGET=global make build-image
        - make build-image
        - make deploy -C global
      if: branch = develop AND type = push

    # we push to production if this is a master branch tagged
    - stage: production
      before_install: []
      env: *envvar
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - TARGET=latest make -C services/maiev-base build-image
        - TARGET=global make build-image
        - make build-image
        - IMAGE_VERSION=${TRAVIS_TAG} make deploy
        - IMAGE_VERSION=latest make deploy
        - docker tag yupeek/maiev:global-latest yupeek/maiev:latest
        - docker push yupeek/maiev:latest
      if: tag IS present

script:
  - make test -C services/$SERVICE


