sudo: false
language: python

services:
  - docker

before_install:
    # start rabbitmq
    - docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3.6.6-management
    # install toxiproxy
    - mkdir $PWD/bin
    - wget -O $PWD/bin/toxiproxy-server https://github.com/Shopify/toxiproxy/releases/download/v2.0.0/toxiproxy-server-linux-amd64
    - chmod +x $PWD/bin/toxiproxy-server
    - export PATH=$PATH:$PWD/bin/
    # work around https://github.com/travis-ci/travis-ci/issues/7940
    - sudo rm -f /etc/boto.cfg

addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox

cache:
  directories:
    - $HOME/.cache/pip

python:
- "3.6"


jobs:
  include:
    - stage: test
      env: SERVICE=common/health_mongodb
    - env: SERVICE=scaler/registry_docker
    - env: SERVICE=scaler/scaler_docker
    - env: SERVICE=overseer/dependency_solver
    - env: SERVICE=overseer/overseer
    - env: SERVICE=overseer/load_manager
    #- env: SERVICE=overseer/upgrade_planer
    - env: SERVICE=monitorer/monitorer_rabbitmq
    - env: SERVICE=monitorer/trigger

script:
  - TARGET=latest make -C services/maiev-base build-image
  - make test -C services/$SERVICE


