sudo: false
language: python

services:
  - docker

before_install:
    # start rabbitmq
    - docker run -d --hostname rabbitmq --name rabbitmq -p 15672:15672 -p 5672:5672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3.6.6-management
    # start mongodb
    - docker run -d --rm --name=maiev_mongodb -p 27017:27017 mongo


addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox

cache:
  directories:
    - $HOME/.cache/pip

python:
- "3.6"


jobs:
  include:
    - stage: test
      env: SERVICE=common/health_mongodb
    - env: SERVICE=scaler/registry_docker
    - env: SERVICE=scaler/scaler_docker
    - env: SERVICE=overseer/dependency_solver
    - env: SERVICE=overseer/overseer
    - env: SERVICE=overseer/load_manager
    - env: SERVICE=overseer/upgrade_planer
    - env: SERVICE=monitorer/monitorer_rabbitmq
    - env: SERVICE=monitorer/trigger
    - stage: global
      script:
      - TARGET=latest make -C services/maiev-base build-image
      - TARGET=global make build-image
      - make test -C global

deploy:
- provider: script
  env:
    - secure: "qtxHIfzPTQcgnPvVy1khUU/ceJQVJFoiF5+L/qfKW8FhIgWdkHExD4PrpkQjzrqsKUi1pqWcj3CXNwSLDzfMqS6rs/CDQFocM3jmCeq8JNm6A7C8C+T4lEZXtGMbdhKSU9cY2rC64vknuHcQ7RDvdn9avumgbXJMzolv67a/6Zy4qAf+BrBLpjWeazHmr4hUV7Ds8DDBgtkrxofqRv6/IrIGWccJAgHZK4hNm7E0JeWCujoSjZu7GhQY5MyuOrErpZ7ood8WD09aFBe5CbNzW6IEFOIGVoQ7ccKi/xY6XXmN/VausqGBFgeXbeGxwbyXAVOjNHr/n0SVkw0jCXj8yWmVkmc1JtWmK1KyqkqXCuB5tJp+obY1dTxgUNqgMGFA+9CqovO6kGEUiJKhRvw7zsnFNGnmrHwbw0UHQOzuJh0NCJXbTw1044GA6OeHYmM2DqQFLLCgUOaKHmLrHZBkW5mzF/kn1PubLuS8uMxnZqWWU1tmfr+8gRe119JL6jzDxEFatHiYLOjfjGof5tsUghEmvw3WXlLrTkDvT0ACxYqQ1N32nntZmraHNpb/pEk49wHHZE9m3nXI+P6b13X0Y0GizTUeaALcEwr2TcChC8ws+vtuKSeXKNbQLUHRzkidsDDHqffP+aflqtB5ZvuR2UQ7+nmRMdqHy3s0AUnidyc="
    - secure: "oZx7FoU0aaS4H3+ST5M+yrv01frGz+083TOzE5q57kD3lXBSexxftc7tuXMaYKdxP7CFCHAcwkfPOUIbYgwwHZrVgHzZVuqyKCji3sgBQDagl5hJTUPwFG0r1L9A5eZFWKm2S0t848mDi6ukPWy/56CYOQPMzu3CKiKYDCqNrZv7hyZx/ZaIwdI4LRqsDp6JjjxvPfBYp2hxr8CL+DILm4iT3pzVhNept3X9Wl1i+YkZ2IrpJYrlDDgq63EWURkA+Nz3N9Tkb+7YeqyJP/gTMnEjl/lbzmuMLxBEDKuU6VJQHArnDbAzNPxrg3HS/ikyVSpHXcGNaIFITWq3xqUIdtcaTeZ/0D+JvEStrFkAJQaLs5PL0LJI8fV+xL5evyW0BXhWuv8+U8JV48hFcO+qMbgff+wYDA9FuLNTyCcOYhx2WwFKP1G85vGO59h6cPehBfms7nTxHoGEiblfeaH4jLFzm/3E23hyA+pJLrurdUnv3I5xYPxgWk+hDa5wzQYW4+QzSbNbsK/1bhJfgrY5kj5ZQ1vCjNDMAgf0tDmel2KXKtkmV2P9qsTcy7hE/uLCO6w9/8ObB7kHWab6G18lMYJF12ZHbBOwkkJ+1ZmfEIFfKE0WazpWh4YER51Xj5v9v4t6aZwVAoRhpfb+YCZSoNklqGK0Sm69siDrIXmLmec="
    - "DOCKER_REPO=yupeek/maiev"
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && IMAGE_VERSION=${TRAVIS_BUILD_NUMBER}b make deploy
  on:
    branch: develop
- provider: script
  env:
    - secure: "qtxHIfzPTQcgnPvVy1khUU/ceJQVJFoiF5+L/qfKW8FhIgWdkHExD4PrpkQjzrqsKUi1pqWcj3CXNwSLDzfMqS6rs/CDQFocM3jmCeq8JNm6A7C8C+T4lEZXtGMbdhKSU9cY2rC64vknuHcQ7RDvdn9avumgbXJMzolv67a/6Zy4qAf+BrBLpjWeazHmr4hUV7Ds8DDBgtkrxofqRv6/IrIGWccJAgHZK4hNm7E0JeWCujoSjZu7GhQY5MyuOrErpZ7ood8WD09aFBe5CbNzW6IEFOIGVoQ7ccKi/xY6XXmN/VausqGBFgeXbeGxwbyXAVOjNHr/n0SVkw0jCXj8yWmVkmc1JtWmK1KyqkqXCuB5tJp+obY1dTxgUNqgMGFA+9CqovO6kGEUiJKhRvw7zsnFNGnmrHwbw0UHQOzuJh0NCJXbTw1044GA6OeHYmM2DqQFLLCgUOaKHmLrHZBkW5mzF/kn1PubLuS8uMxnZqWWU1tmfr+8gRe119JL6jzDxEFatHiYLOjfjGof5tsUghEmvw3WXlLrTkDvT0ACxYqQ1N32nntZmraHNpb/pEk49wHHZE9m3nXI+P6b13X0Y0GizTUeaALcEwr2TcChC8ws+vtuKSeXKNbQLUHRzkidsDDHqffP+aflqtB5ZvuR2UQ7+nmRMdqHy3s0AUnidyc="
    - secure: "oZx7FoU0aaS4H3+ST5M+yrv01frGz+083TOzE5q57kD3lXBSexxftc7tuXMaYKdxP7CFCHAcwkfPOUIbYgwwHZrVgHzZVuqyKCji3sgBQDagl5hJTUPwFG0r1L9A5eZFWKm2S0t848mDi6ukPWy/56CYOQPMzu3CKiKYDCqNrZv7hyZx/ZaIwdI4LRqsDp6JjjxvPfBYp2hxr8CL+DILm4iT3pzVhNept3X9Wl1i+YkZ2IrpJYrlDDgq63EWURkA+Nz3N9Tkb+7YeqyJP/gTMnEjl/lbzmuMLxBEDKuU6VJQHArnDbAzNPxrg3HS/ikyVSpHXcGNaIFITWq3xqUIdtcaTeZ/0D+JvEStrFkAJQaLs5PL0LJI8fV+xL5evyW0BXhWuv8+U8JV48hFcO+qMbgff+wYDA9FuLNTyCcOYhx2WwFKP1G85vGO59h6cPehBfms7nTxHoGEiblfeaH4jLFzm/3E23hyA+pJLrurdUnv3I5xYPxgWk+hDa5wzQYW4+QzSbNbsK/1bhJfgrY5kj5ZQ1vCjNDMAgf0tDmel2KXKtkmV2P9qsTcy7hE/uLCO6w9/8ObB7kHWab6G18lMYJF12ZHbBOwkkJ+1ZmfEIFfKE0WazpWh4YER51Xj5v9v4t6aZwVAoRhpfb+YCZSoNklqGK0Sm69siDrIXmLmec="
    - "DOCKER_REPO=yupeek/maiev"
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && IMAGE_VERSION=${TRAVIS_TAG} make deploy
  on:
    branch: master
    tags: true

script:
  - TARGET=latest make -C services/maiev-base build-image
  - make test -C services/$SERVICE


