AMQP_URI: amqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASSWORD:guest}@${RABBITMQ_HOST:localhost}
WEB_SERVER_ADDRESS: '0.0.0.0:8000'
MONITORED_SERVER_URL: http://guest:guest@192.168.253.139:15672/api/

serializer: json_datecompatible

LOGGING:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    colored:
      format: "\u001B[1;33m%(levelname)s\u001B[0m [\u001B[1;31m%(name)s\
        \u001B[0m:\u001B[1;32m%(lineno)s\
        \u001B[0m:\u001B[1;35m%(funcName)s\u001B[0m] \u001B[1;37m%(message)s\u001B[0m"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: colored
  loggers:
    service:
      level: DEBUG
      handlers: [console]
    components:
      level: DEBUG
      handlers: [console]
    nameko:
      level: ERROR
      handlers: [console]